#[derive(Debug, Copy, Clone, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct Registers {
    pub mode_test_21: [u8; 8],
    pub mode_test_2c: [u8; 8],
    pub mode_ch3: u8,
    pub mode_kon_channel: u8,
    pub mode_kon_operator: [u8; 4],
    pub mode_kon: [u8; 24],
    pub mode_csm: u8,
    pub mode_kon_csm: u8,
    pub dac_enable: bool,
    pub dac_data: i16,
    pub rate_scale: [u8; 24],
    pub attack_rate: [u8; 24],
    pub decay_rate_second: [u8; 24],
    pub detune: [u8; 24],
    pub multiple: [u8; 24],
    pub secondary_amplitude: [u8; 24],
    pub release_rate: [u8; 24],
    pub decay_rate_first: [u8; 24],
    pub amplitude_modulation: [u8; 24],
    pub total_level: [u8; 24],
    pub ssg_eg: [u8; 24],
    pub fnum: [u16; 6],
    pub block: [u8; 6],
    pub kcode: [u8; 6],
    pub fnum_ch3: [u16; 6],
    pub block_ch3: [u8; 6],
    pub kcode_ch3: [u8; 6],
    pub block_freq: u8,
    pub block_freq_ch3: u8,
    pub connect: [u8; 6],
    pub feedback: [u8; 6],
    pub pan_l: [u8; 6],
    pub pan_r: [u8; 6],
    pub amp_mod_sens: [u8; 6],
    pub freq_mod_sens: [u8; 6],
    pub status: u8,
    pub status_time: u32,
}

impl Default for Registers {
    fn default() -> Self {
        Registers {
            mode_test_21: [0; 8],
            mode_test_2c: [0; 8],
            mode_ch3: 0,
            mode_kon_channel: 0,
            mode_kon_operator: [0; 4],
            mode_kon: [0; 24],
            mode_csm: 0,
            mode_kon_csm: 0,
            dac_enable: false,
            dac_data: 0,
            rate_scale: [0; 24],
            attack_rate: [0; 24],
            decay_rate_second: [0; 24],
            detune: [0; 24],
            multiple: [1; 24],
            secondary_amplitude: [0; 24],
            release_rate: [0; 24],
            decay_rate_first: [0; 24],
            amplitude_modulation: [0; 24],
            total_level: [0; 24],
            ssg_eg: [0; 24],
            fnum: [0; 6],
            block: [0; 6],
            kcode: [0; 6],
            fnum_ch3: [0; 6],
            block_ch3: [0; 6],
            kcode_ch3: [0; 6],
            block_freq: 0,
            block_freq_ch3: 0,
            connect: [0; 6],
            feedback: [0; 6],
            pan_l: [1; 6],
            pan_r: [1; 6],
            amp_mod_sens: [0; 6],
            freq_mod_sens: [0; 6],
            status: 0,
            status_time: 0,
        }
    }
}
