/*
pub fn grand_piano() -> ChannelState {
    ChannelState::default()
        .with_feedback(Feedback::Feedback6)
        .with_algorithm(Algorithm::Algorithm2)
        .with_stereo_output(StereoOutput::new(true, true))
        .with_amplitude_modulation_sensitivity(AmplitudeModulationSensitivity::Db0)
        .with_frequency_modulation_sensitivity(FrequencyModulationSensitivity::Ht0)
        .with_operator(
            Operator1,
            OperatorState::default()
                .with_detune(Minus3)
                .with_multiple(Mul1)
                .with_total_level(35)
                .with_rate_scaling(1)
                .with_attack_rate(31)
                .with_amplitude(0)
                .with_first_decay_rate(5)
                .with_second_decay_rate(2)
                .with_second_amplitude(1)
                .with_release_rate(1)
                .with_software_sound_generator(SoftwareSoundGeneratorMode::DISABLED),
        )
        .with_operator(
            Operator2,
            OperatorState::default()
                .with_detune(Plus0)
                .with_multiple(Mul13)
                .with_total_level(45)
                .with_rate_scaling(2)
                .with_attack_rate(25)
                .with_amplitude(0)
                .with_first_decay_rate(5)
                .with_second_decay_rate(2)
                .with_second_amplitude(1)
                .with_release_rate(1)
                .with_software_sound_generator(SoftwareSoundGeneratorMode::DISABLED),
        )
        .with_operator(
            Operator3,
            OperatorState::default()
                .with_detune(Plus3)
                .with_multiple(Mul3)
                .with_total_level(38)
                .with_rate_scaling(1)
                .with_attack_rate(31)
                .with_amplitude(0)
                .with_first_decay_rate(5)
                .with_second_decay_rate(2)
                .with_second_amplitude(1)
                .with_release_rate(1)
                .with_software_sound_generator(SoftwareSoundGeneratorMode::DISABLED),
        )
        .with_operator(
            Operator4,
            OperatorState::default()
                .with_detune(Plus0)
                .with_multiple(Mul1)
                .with_total_level(0)
                .with_rate_scaling(2)
                .with_attack_rate(20)
                .with_amplitude(0)
                .with_first_decay_rate(7)
                .with_second_decay_rate(2)
                .with_second_amplitude(10)
                .with_release_rate(6)
                .with_software_sound_generator(SoftwareSoundGeneratorMode::DISABLED),
        )
}
*/