[package]
name = "opn2-nuked"
version = "0.1.0"
authors = ["Josh Palmer <jpalmerwatkins@gmail.com>"]
edition = "2018"

[dependencies]
opn2-trait = { path = "../opn2-trait" }
libnuked-opn2-sys = { path = "../libnuked-opn2-sys" }
